class Awareness:
    """认知id"""

    KNOW_TEMPERAMENT = "know_temperament"
    """ 了解该角色的性格 """
    KNOW_IDENTITY = "know_identity"
    """ 了解该角色的身份 """
    KNOW_GENDER = "know_gender"
    """ 了解该角色的性别 """
    KNOW_POSITION = "know_position"
    """ 了解该角色的所处位置 """
    KNOW_HUMANITY = "know_humanity"
    """ 了解该角色的人文水平 """
    KNOW_SKILLS = "know_skills"
    """ 了解该角色的技巧水平 """
    KNOW_SCIENCE = "know_science"
    """ 了解该角色的科学知识水平 """
    KNOW_MYSTICS = "know_mystics"
    """ 了解该角色的神秘学知识水平 """
    KNOW_LANGUAGE = "know_language"
    """ 了解该角色的语言水平 """
    KNOW_HUMANITY_INTEREST = "know_humanity_interest"
    """ 了解该角色的人文天赋水平 """
    KNOW_SKILLS_INTEREST = "know_skills_interest"
    """ 了解该角色的技巧天赋水平 """
    KNOW_SCIENCE_INTEREST = "know_science_interest"
    """ 了解该角色的科学知识天赋水平 """
    KNOW_MYSTICS_INTEREST = "know_mystics_interest"
    """ 了解该角色的神秘学天赋水平 """
    KNOW_LANGUAGE_INTEREST = "know_language_interest"
    """ 了解该角色的语言天赋水平 """
    KNOW_LIKE_DRESSING_STYLE = "know_like_dressing_style"
    """ 了解该角色喜欢的穿搭风格 """
    KNOW_MENTAL_STATUS = "know_mental_status"
    """ 了解该角色的心灵状态 """
    KNOW_BODILY_STATUS = "know_bodily_status"
    """ 了解该角色的肉体状态 """
    KNOW_STATURE = "know_stature"
    """ 了解该角色的身材 """
    KNOW_WEARS = "know_wears"
    """ 了解该角色当前的穿着 """
    KNOW_SEX_EXPERIENCE = "know_sex_experience"
    """ 了解该角色的性经验 """
    KNOW_SOCIAL_STATUS = "know_social_status"
    """ 了解该角色的社交关系 """

