class Behavior:
    """行为id"""

    SHARE_BLANKLY = 0
    """ 发呆 """
    MOVE = 1
    """ 移动 """
    REST = 2
    """ 休息 """
    ATTEND_CLASS = 3
    """ 上课 """
    EAT = 4
    """ 进食 """
    CHAT = 5
    """ 闲聊 """
    PLAY_PIANO = 6
    """ 弹钢琴 """
    SINGING = 7
    """ 唱歌 """
    TOUCH_HEAD = 8
    """ 摸头 """
    SLEEP = 9
    """ 睡觉 """
    EMBRACE = 10
    """ 拥抱 """
    KISS = 11
    """ 亲吻 """
    HAND_IN_HAND = 12
    """ 牵手 """
    DEAD = 13
    """ 死亡 """
    STROKE = 14
    """ 抚摸 """
    TOUCH_CHEST = 15
    """ 摸胸 """
    TEACHING = 16
    """ 教学 """
    PLAY_GUITAR = 17
    """ 弹吉他 """
    SELF_STUDY = 18
    """ 自习 """
    MASTURBATION = 19
    """ 手淫 """
    DANCE = 20
    """ 跳舞 """
    ABUSE = 21
    """ 辱骂 """
    TARGET_UNDRESS = 22
    """ 脱对方衣服 """
    WEAR = 23
    """ 穿衣 """
    UNDRESS = 24
    """ 脱衣 """
    MISSIONARY_POSITION_MALE = 25
    """ 正常体位(男) """
    MISSIONARY_POSITION_FEMALE = 26
    """ 正常体位(女) """
    SIESTA = 27
    """ 午睡 """
