class BookType:
    """书籍分类"""
    PRIMARY_SCHOOL_GRADE_1 = 0
    PRIMARY_SCHOOL_GRADE_2 = 1
    PRIMARY_SCHOOL_GRADE_3 = 2
    PRIMARY_SCHOOL_GRADE_4 = 3
    PRIMARY_SCHOOL_GRADE_5 = 4
    PRIMARY_SCHOOL_GRADE_6 = 5
    JUNIOR_HIGH_SCHOOL_GRADE_1 = 6
    JUNIOR_HIGH_SCHOOL_GRADE_2 = 7
    JUNIOR_HIGH_SCHOOL_GRADE_3 = 8
    SENIOR_HIGH_SCHOOL_GRADE_1 = 9
    SENIOR_HIGH_SCHOOL_GRADE_2 = 10
    SENIOR_HIGH_SCHOOL_GRADE_3 = 11
