class CharacterStatus:
    """角色状态id"""

    STATUS_ARDER = 0
    """ 休闲状态 """
    STATUS_MOVE = 1
    """ 移动状态 """
    STATUS_REST = 2
    """ 休息状态 """
    STATUS_ATTEND_CLASS = 3
    """ 上课状态 """
    STATUS_EAT = 4
    """ 进食状态 """
    STATUS_CHAT = 5
    """ 闲聊状态 """
    STATUS_PLAY_PIANO = 6
    """ 弹钢琴 """
    STATUS_SINGING = 7
    """ 唱歌 """
    STATUS_TOUCH_HEAD = 8
    """ 摸头 """
    STATUS_SLEEP = 9
    """ 睡觉 """
    STATUS_EMBRACE = 10
    """ 拥抱 """
    STATUS_KISS = 11
    """ 亲吻 """
    STATUS_HAND_IN_HAND = 12
    """ 牵手 """
    STATUS_DEAD = 13
    """ 死亡 """
    STATUS_STROKE = 14
    """ 抚摸 """
    STATUS_TOUCH_CHEST = 15
    """ 摸胸 """
    STATUS_TEACHING = 16
    """ 教学 """
    STATUS_PLAY_GUITAR = 17
    """ 弹吉他 """
    STATUS_SELF_STUDY = 18
    """ 自习 """
    STATUS_MASTURBATION = 19
    """ 手淫 """
    STATUS_DANCE = 20
    """ 跳舞 """
    STATUS_ABUSE = 21
    """ 辱骂 """
    STATUS_TARGET_UNDRESS = 22
    """ 脱对方衣服 """
    STATUS_WEAR = 23
    """ 穿衣 """
    STATUS_UNDRESS = 24
    """ 脱衣 """
    STATUS_MISSIONARY_POSITION_MALE = 25
    """ 正常体位(男) """
    STATUS_MISSIONARY_POSITION_FEMALE = 26
    """ 正常体位(女) """
    STATUS_SIESTA = 27
    """ 午睡 """
    STATUS_GENERAL_SPEECH = 28
    """ 演讲 """
    STATUS_SEE_STAR = 29
    """ 看星星 """
